// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gaia/usc/v1beta1/usc.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the x/usc module.
type Params struct {
	// redeem_dur defines USC -> collateral redeem duration (how long does it takes to convert).
	RedeemDur time.Duration `protobuf:"bytes,1,opt,name=redeem_dur,json=redeemDur,proto3,stdduration" json:"redeem_dur" yaml:"redeem_dur"`
	// collateral_denoms defines a set of collateral coin denoms that are supported by the module.
	CollateralDenoms []string `protobuf:"bytes,2,rep,name=collateral_denoms,json=collateralDenoms,proto3" json:"collateral_denoms,omitempty" yaml:"collateral_denoms"`
	// usc_denom defines the USC coin denom.
	UscDenom string `protobuf:"bytes,3,opt,name=usc_denom,json=uscDenom,proto3" json:"usc_denom,omitempty" yaml:"usc_denom"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8575b09df2fdc43e, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// RedeemEntry defines the redeeming queue entry.
type RedeemEntry struct {
	Address          string       `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	CollateralAmount []types.Coin `protobuf:"bytes,2,rep,name=collateral_amount,json=collateralAmount,proto3" json:"collateral_amount"`
}

func (m *RedeemEntry) Reset()         { *m = RedeemEntry{} }
func (m *RedeemEntry) String() string { return proto.CompactTextString(m) }
func (*RedeemEntry) ProtoMessage()    {}
func (*RedeemEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_8575b09df2fdc43e, []int{1}
}
func (m *RedeemEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RedeemEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RedeemEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RedeemEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemEntry.Merge(m, src)
}
func (m *RedeemEntry) XXX_Size() int {
	return m.Size()
}
func (m *RedeemEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemEntry.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemEntry proto.InternalMessageInfo

type RedeemEntries struct {
	Entries []RedeemEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries"`
}

func (m *RedeemEntries) Reset()         { *m = RedeemEntries{} }
func (m *RedeemEntries) String() string { return proto.CompactTextString(m) }
func (*RedeemEntries) ProtoMessage()    {}
func (*RedeemEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_8575b09df2fdc43e, []int{2}
}
func (m *RedeemEntries) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RedeemEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RedeemEntries.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RedeemEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedeemEntries.Merge(m, src)
}
func (m *RedeemEntries) XXX_Size() int {
	return m.Size()
}
func (m *RedeemEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_RedeemEntries.DiscardUnknown(m)
}

var xxx_messageInfo_RedeemEntries proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "gaia.usc.v1beta1.Params")
	proto.RegisterType((*RedeemEntry)(nil), "gaia.usc.v1beta1.RedeemEntry")
	proto.RegisterType((*RedeemEntries)(nil), "gaia.usc.v1beta1.RedeemEntries")
}

func init() { proto.RegisterFile("gaia/usc/v1beta1/usc.proto", fileDescriptor_8575b09df2fdc43e) }

var fileDescriptor_8575b09df2fdc43e = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x3d, 0x6f, 0xd4, 0x40,
	0x10, 0xf5, 0x12, 0x94, 0xc4, 0x1b, 0x21, 0x5d, 0xac, 0x14, 0xe6, 0xa4, 0xd8, 0x27, 0x57, 0x27,
	0x24, 0x76, 0x75, 0xd0, 0x45, 0xa2, 0xc0, 0x39, 0x24, 0x0a, 0x90, 0x90, 0x11, 0x02, 0xd1, 0x44,
	0x6b, 0x7b, 0x31, 0x96, 0x6c, 0xcf, 0x69, 0x3f, 0x22, 0xae, 0xe2, 0x2f, 0x50, 0xa6, 0xcc, 0xcf,
	0xb9, 0x32, 0x25, 0xd5, 0x01, 0x77, 0x0d, 0x0d, 0x4d, 0x7e, 0x01, 0xf2, 0xae, 0x1d, 0x07, 0xd2,
	0xcd, 0xcc, 0x9b, 0xf7, 0xf6, 0xed, 0xcc, 0xe0, 0x71, 0xc1, 0x4a, 0x46, 0xb5, 0xcc, 0xe8, 0xf9,
	0x2c, 0xe5, 0x8a, 0xcd, 0xda, 0x98, 0x2c, 0x04, 0x28, 0xf0, 0x46, 0x2d, 0x46, 0xda, 0xbc, 0xc3,
	0xc6, 0x47, 0x05, 0x14, 0x60, 0x40, 0xda, 0x46, 0xb6, 0x6f, 0x1c, 0x14, 0x00, 0x45, 0xc5, 0xa9,
	0xc9, 0x52, 0xfd, 0x89, 0xe6, 0x5a, 0x30, 0x55, 0x42, 0xd3, 0xe3, 0x19, 0xc8, 0x1a, 0x24, 0x4d,
	0x99, 0xe4, 0x37, 0xcf, 0x64, 0x50, 0x76, 0x78, 0xf4, 0x07, 0xe1, 0xdd, 0x37, 0x4c, 0xb0, 0x5a,
	0x7a, 0xef, 0x31, 0x16, 0x3c, 0xe7, 0xbc, 0x3e, 0xcb, 0xb5, 0xf0, 0xd1, 0x04, 0x4d, 0x0f, 0x9e,
	0x3c, 0x24, 0x56, 0x9f, 0xf4, 0xfa, 0x64, 0xde, 0xe9, 0xc7, 0xc7, 0xab, 0x75, 0xe8, 0x5c, 0xaf,
	0xc3, 0xc3, 0x25, 0xab, 0xab, 0x93, 0x68, 0xa0, 0x46, 0x17, 0x3f, 0x42, 0x94, 0xb8, 0xb6, 0x30,
	0xd7, 0xc2, 0x7b, 0x8d, 0x0f, 0x33, 0xa8, 0x2a, 0xa6, 0xb8, 0x60, 0xd5, 0x59, 0xce, 0x1b, 0xa8,
	0xa5, 0x7f, 0x6f, 0xb2, 0x33, 0x75, 0xe3, 0x49, 0x27, 0xe2, 0x5b, 0x91, 0x3b, 0x6d, 0x51, 0x32,
	0x1a, 0x6a, 0x73, 0x53, 0xf2, 0x66, 0xd8, 0xd5, 0x32, 0xb3, 0x0d, 0xfe, 0xce, 0x04, 0x4d, 0xdd,
	0xf8, 0xe8, 0x7a, 0x1d, 0x8e, 0xac, 0xc4, 0x0d, 0x14, 0x25, 0xfb, 0x5a, 0x66, 0x86, 0x73, 0xb2,
	0x7f, 0x71, 0x19, 0x3a, 0xbf, 0x2f, 0x43, 0x14, 0x7d, 0xc5, 0x07, 0x89, 0x31, 0xf6, 0xa2, 0x51,
	0x62, 0xe9, 0xf9, 0x78, 0x8f, 0xe5, 0xb9, 0xe0, 0x52, 0x9a, 0x0f, 0xbb, 0x49, 0x9f, 0x7a, 0xaf,
	0xfe, 0x31, 0xcd, 0x6a, 0xd0, 0x8d, 0x32, 0xa6, 0xdb, 0xa1, 0xd8, 0xa1, 0x92, 0x76, 0xa8, 0xfd,
	0x7e, 0xc8, 0x29, 0x94, 0x4d, 0x7c, 0xbf, 0xfd, 0xcf, 0x6d, 0xcf, 0xcf, 0x0d, 0xd1, 0x18, 0x40,
	0xc6, 0xc0, 0x07, 0xfc, 0x60, 0x30, 0x50, 0x72, 0xe9, 0x3d, 0xc3, 0x7b, 0xdc, 0x86, 0x3e, 0x32,
	0xf2, 0xc7, 0xe4, 0xff, 0xdd, 0x93, 0x5b, 0x96, 0xbb, 0x27, 0x7a, 0xce, 0xa0, 0x1c, 0xbf, 0x5c,
	0xfd, 0x0a, 0x9c, 0xd5, 0x26, 0x40, 0x57, 0x9b, 0x00, 0xfd, 0xdc, 0x04, 0xe8, 0xdb, 0x36, 0x70,
	0xae, 0xb6, 0x81, 0xf3, 0x7d, 0x1b, 0x38, 0x1f, 0x1f, 0x15, 0xa5, 0xfa, 0xac, 0x53, 0x92, 0x41,
	0x4d, 0xdf, 0xbd, 0x3d, 0x7d, 0x3c, 0xe7, 0xe7, 0xbc, 0x82, 0x05, 0x17, 0x92, 0x9a, 0x33, 0xfc,
	0x62, 0x0e, 0x51, 0x2d, 0x17, 0x5c, 0xa6, 0xbb, 0x66, 0xdb, 0x4f, 0xff, 0x06, 0x00, 0x00, 0xff,
	0xff, 0x96, 0xe5, 0x82, 0x5e, 0xa1, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.RedeemDur != that1.RedeemDur {
		return false
	}
	if len(this.CollateralDenoms) != len(that1.CollateralDenoms) {
		return false
	}
	for i := range this.CollateralDenoms {
		if this.CollateralDenoms[i] != that1.CollateralDenoms[i] {
			return false
		}
	}
	if this.UscDenom != that1.UscDenom {
		return false
	}
	return true
}
func (this *RedeemEntry) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RedeemEntry)
	if !ok {
		that2, ok := that.(RedeemEntry)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	if len(this.CollateralAmount) != len(that1.CollateralAmount) {
		return false
	}
	for i := range this.CollateralAmount {
		if !this.CollateralAmount[i].Equal(&that1.CollateralAmount[i]) {
			return false
		}
	}
	return true
}
func (this *RedeemEntries) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RedeemEntries)
	if !ok {
		that2, ok := that.(RedeemEntries)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Entries) != len(that1.Entries) {
		return false
	}
	for i := range this.Entries {
		if !this.Entries[i].Equal(&that1.Entries[i]) {
			return false
		}
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UscDenom) > 0 {
		i -= len(m.UscDenom)
		copy(dAtA[i:], m.UscDenom)
		i = encodeVarintUsc(dAtA, i, uint64(len(m.UscDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CollateralDenoms) > 0 {
		for iNdEx := len(m.CollateralDenoms) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CollateralDenoms[iNdEx])
			copy(dAtA[i:], m.CollateralDenoms[iNdEx])
			i = encodeVarintUsc(dAtA, i, uint64(len(m.CollateralDenoms[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.RedeemDur, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.RedeemDur):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintUsc(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *RedeemEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RedeemEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RedeemEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CollateralAmount) > 0 {
		for iNdEx := len(m.CollateralAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CollateralAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintUsc(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintUsc(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RedeemEntries) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RedeemEntries) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RedeemEntries) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for iNdEx := len(m.Entries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Entries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintUsc(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintUsc(dAtA []byte, offset int, v uint64) int {
	offset -= sovUsc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.RedeemDur)
	n += 1 + l + sovUsc(uint64(l))
	if len(m.CollateralDenoms) > 0 {
		for _, s := range m.CollateralDenoms {
			l = len(s)
			n += 1 + l + sovUsc(uint64(l))
		}
	}
	l = len(m.UscDenom)
	if l > 0 {
		n += 1 + l + sovUsc(uint64(l))
	}
	return n
}

func (m *RedeemEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovUsc(uint64(l))
	}
	if len(m.CollateralAmount) > 0 {
		for _, e := range m.CollateralAmount {
			l = e.Size()
			n += 1 + l + sovUsc(uint64(l))
		}
	}
	return n
}

func (m *RedeemEntries) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Entries) > 0 {
		for _, e := range m.Entries {
			l = e.Size()
			n += 1 + l + sovUsc(uint64(l))
		}
	}
	return n
}

func sovUsc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUsc(x uint64) (n int) {
	return sovUsc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedeemDur", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUsc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUsc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.RedeemDur, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralDenoms", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralDenoms = append(m.CollateralDenoms, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UscDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UscDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUsc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RedeemEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RedeemEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RedeemEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollateralAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUsc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUsc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollateralAmount = append(m.CollateralAmount, types.Coin{})
			if err := m.CollateralAmount[len(m.CollateralAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUsc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RedeemEntries) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RedeemEntries: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RedeemEntries: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUsc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUsc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Entries = append(m.Entries, RedeemEntry{})
			if err := m.Entries[len(m.Entries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUsc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUsc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUsc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUsc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUsc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUsc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUsc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUsc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUsc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUsc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUsc = fmt.Errorf("proto: unexpected end of group")
)
